[vars]
secrets = """
BROKER__API_KEY
BROKER__API_SECRET
FINNHUB__API_KEY
WEB__LOGIN_SECRET
REDIS__URL
LOGIN__OAUTH_CLIENT_SECRET
LOGIN__ALLOWED_EMAILS
"""

[env]
PORT = "8080"

_.file = { path = ".env.production", redact = true }
