[vars]
secrets = """
BROKER__API_KEY
BROKER__API_SECRET
FINNHUB__API_KEY
WEB__LOGIN_SECRET
REDIS__URL
LOGIN__OAUTH_CLIENT_SECRET
LOGIN__ALLOWED_EMAILS
RAILWAY_TOKEN
"""

[env]
PORT = "8080"
WEB__BASE_URL = "https://money-tree-web-production.up.railway.app"

## login
LOGIN__OAUTH_CLIENT_ID = "rlwy_oaci_29D1XXdSqj23u2HgdYlbq8ch"

_.file = { path = ".env.production", redact = true }
